# Generated by Django 4.2.2 on 2024-10-04 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("timesystem", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClockInRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clock_in_time", models.DateTimeField()),
                ("clock_out_time", models.DateTimeField(blank=True, null=True)),
                ("total_hours", models.FloatField(default=0)),
                ("extra_hours", models.FloatField(default=0)),
                ("job_name", models.CharField(blank=True, max_length=255, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Break",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("break_type", models.CharField(max_length=50)),
                ("break_start", models.DateTimeField()),
                ("break_end", models.DateTimeField(blank=True, null=True)),
                ("break_notes", models.TextField()),
                (
                    "clock_in_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breaks",
                        to="timesystem.clockinrecord",
                    ),
                ),
            ],
        ),
    ]
