# Generated by Django 4.2.2 on 2024-10-07 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("timesystem", "0002_clockinrecord_break"),
    ]

    operations = [
        migrations.CreateModel(
            name="BreakRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "break_type",
                    models.CharField(
                        choices=[("tea", "Tea Break"), ("lunch", "Lunch Break")],
                        max_length=20,
                    ),
                ),
                ("break_notes", models.TextField(blank=True, null=True)),
                (
                    "time_started",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("time_ended", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="JobRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name="clockinrecord",
            old_name="clock_out_time",
            new_name="time_clocked_out",
        ),
        migrations.RemoveField(
            model_name="clockinrecord",
            name="clock_in_time",
        ),
        migrations.RemoveField(
            model_name="clockinrecord",
            name="job_name",
        ),
        migrations.RemoveField(
            model_name="clockinrecord",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="clockinrecord",
            name="total_hours",
        ),
        migrations.AddField(
            model_name="clockinrecord",
            name="hours_worked",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="clockinrecord",
            name="time_clocked_in",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="clockinrecord",
            name="extra_hours",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.DeleteModel(
            name="Break",
        ),
        migrations.AddField(
            model_name="jobrecord",
            name="clock_in_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="timesystem.clockinrecord",
            ),
        ),
        migrations.AddField(
            model_name="jobrecord",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="breakrecord",
            name="clock_in_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="timesystem.clockinrecord",
            ),
        ),
    ]
