# Generated by Django 4.2.2 on 2024-10-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "timesystem",
            "0004_remove_task_project_task_assigned_to_task_completed_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
