# Generated by Django 4.2.2 on 2024-10-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesystem", "0007_remove_task_completed_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("awaiting_approval", "Awaiting Approval"),
                    ("extension_approved", "Extension Approved"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
