# Generated by Django 4.2.2 on 2024-10-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesystem", "0008_task_notes_alter_task_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_name", models.CharField(max_length=100)),
                ("employee_id", models.CharField(max_length=10)),
                ("employee_email", models.CharField(max_length=100)),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("ANNUAL", "Annual Leave"),
                            ("SICK", "Sick Leave"),
                            ("CASUAL", "Casual Leave"),
                            ("MATERNITY", "Maternity Leave"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.TextField()),
                ("status", models.CharField(default="PENDING", max_length=10)),
            ],
        ),
    ]
