# Generated by Django 4.2.2 on 2024-10-15 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("timesystem", "0010_leavebalance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leaverequest",
            name="employee_id",
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="employee_email",
            field=models.EmailField(max_length=100),
        ),
    ]
