# Generated by Django 4.2.2 on 2024-10-26 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("timesystem", "0014_alter_task_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="timesystem.project",
            ),
            preserve_default=False,
        ),
    ]
