# Generated by Django 4.2.2 on 2024-10-16 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "admin_dashboard",
            "0002_alter_timeentry_employee_alter_timeentry_project_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leavebalance",
            name="user",
        ),
        migrations.RemoveField(
            model_name="leaverequest",
            name="user",
        ),
        migrations.RemoveField(
            model_name="project",
            name="employees",
        ),
        migrations.RemoveField(
            model_name="task",
            name="assigned_to",
        ),
        migrations.RemoveField(
            model_name="timeentry",
            name="employee",
        ),
        migrations.RemoveField(
            model_name="timeentry",
            name="project",
        ),
        migrations.DeleteModel(
            name="ClockInRecord",
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
        migrations.DeleteModel(
            name="LeaveBalance",
        ),
        migrations.DeleteModel(
            name="LeaveRequest",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="Task",
        ),
        migrations.DeleteModel(
            name="TimeEntry",
        ),
    ]
